// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXnakMYNbLxMl-l36mx3xJMsbPUP5f-k',
    appId: '1:934036029735:android:973b546cba4b455d122902',
    messagingSenderId: '934036029735',
    projectId: 'calendar-a0fb8',
    databaseURL: 'https://calendar-a0fb8-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-a0fb8.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZEY1GnPHNEfqIg8OWoLXa9QqfSyXQ18',
    appId: '1:934036029735:web:cfde3981adee6815122902',
    messagingSenderId: '934036029735',
    projectId: 'calendar-a0fb8',
    authDomain: 'calendar-a0fb8.firebaseapp.com',
    databaseURL: 'https://calendar-a0fb8-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-a0fb8.appspot.com',
    measurementId: 'G-DL3F5JJDV7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK67E9BpG16wxci2oyDWbJcPG1QzbT2e0',
    appId: '1:934036029735:ios:d909f5f47b77ddfa122902',
    messagingSenderId: '934036029735',
    projectId: 'calendar-a0fb8',
    databaseURL: 'https://calendar-a0fb8-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-a0fb8.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK67E9BpG16wxci2oyDWbJcPG1QzbT2e0',
    appId: '1:934036029735:ios:d909f5f47b77ddfa122902',
    messagingSenderId: '934036029735',
    projectId: 'calendar-a0fb8',
    databaseURL: 'https://calendar-a0fb8-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-a0fb8.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZEY1GnPHNEfqIg8OWoLXa9QqfSyXQ18',
    appId: '1:934036029735:web:d89795aa5b4a3801122902',
    messagingSenderId: '934036029735',
    projectId: 'calendar-a0fb8',
    authDomain: 'calendar-a0fb8.firebaseapp.com',
    databaseURL: 'https://calendar-a0fb8-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-a0fb8.appspot.com',
    measurementId: 'G-GDK2BCB6T9',
  );

}